version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051" 
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './weaviate_data'
      DEFAULT_VECTORIZER_MODULE: 'none'   # You use your own embeddings
      ENABLE_MODULES: 'text2vec-openai'
      ENABLE_GRPC: "true"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    
  rag-aws-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    environment:
      WEAVIATE_HTTP_HOST: 'weaviate'
      WEAVIATE_HTTP_PORT: '8080'
      WEAVIATE_GRPC_HOST: 'weaviate'
      WEAVIATE_GRPC_PORT: '50051'
      # Add any other env vars your app needs here
