version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051" 
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './weaviate_data'
      DEFAULT_VECTORIZER_MODULE: 'none'   # You use your own embeddings
      ENABLE_MODULES: 'text2vec-openai'
      ENABLE_GRPC: "true"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
